### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by nikoblessd** [xhsu/metamod-AmxModules#1]
hi, do you have discord?

**Comment by xhsu** [comment]
Hi,
Yes I do. Is there anything specific you need to discuss?

**Comment by nikoblessd** [comment]
yes, I wanted to ask you a question privately.

**Comment by xhsu** [comment]
I am afraid if it can't be discussed publicly, I have nothing to say to a
unknown person on internet.

Unless, of course, it's a blackmail or relatating to my IRL identity.😆

**Comment by nikoblessd** [comment]
Well, I just wanted to ask you for a job, obviously paid. I don't know if it's possible.

**Comment by xhsu** [comment]
It's pretty cool and my pleasure to receive such an invitation, but I am no
professional programmer but an enthusiastic for CSCZ/CS1.6 (not even CSGO!)
You sure about that?

**Comment by nikoblessd** [comment]
Sure, it's about an amxx module, I don't think it's complicated for you.

**Comment by xhsu** [comment]
Alright, should you wish to discuss it privately then DM me on discord:
anthocyanidin

**Comment by xhsu** [comment]
#fd9a158
Module published for free.
